"""
Which evolution family each Pokemon belongs to.

Used so a deck isn't named after two stages of the same Pokemon --
"Garchomp ex / Gabite" -- when the second name is only there because
Gabite's ability fired every turn. Comparing the start of the names used
to stand in for this and got it wrong whenever a line's names don't
share one: Gible, Gabite and Garchomp; Dreepy, Drakloak and Dragapult;
Ralts, Kirlia and Gardevoir.

FAMILY maps each species, as PokeAPI names it, to its evolution chain
number: two species with the same number are one line. Generated from
PokeAPI's pokemon_species.csv (github.com/PokeAPI/pokeapi), 1025
species. Regenerate when new Pokemon come out; anything not in here
falls back to the old name comparison, so a missing entry degrades
gracefully rather than breaking anything.
"""

import re
import unicodedata

FAMILY = {
    "abomasnow":239,"abra":27,"absol":185,"accelgor":312,"aegislash":349,
    "aerodactyl":71,"aggron":151,"aipom":93,"alakazam":27,"alcremie":452,
    "alomomola":302,"altaria":168,"amaura":358,"ambipom":93,"amoonguss":300,
    "ampharos":89,"annihilape":24,"anorith":177,"appletun":442,"applin":442,
    "araquanid":387,"arbok":9,"arboliva":487,"arcanine":25,"arceus":254,
    "archaludon":465,"archen":289,"archeops":289,"arctibax":527,"arctovish":464,
    "arctozolt":462,"ariados":85,"armaldo":177,"armarouge":490,"aromatisse":350,
    "aron":151,"arrokuda":445,"articuno":73,"audino":271,"aurorus":358,
    "avalugg":366,"axew":309,"azelf":243,"azumarill":90,"azurill":90,
    "bagon":191,"baltoy":175,"banette":181,"barbaracle":353,"barboach":173,
    "barraskewda":445,"basculegion":280,"basculin":280,"bastiodon":212,
    "baxcalibur":527,"bayleef":79,"beartic":310,"beautifly":135,"beedrill":5,
    "beheeyem":307,"beldum":192,"bellibolt":491,"bellossom":18,"bellsprout":29,
    "bergmite":366,"bewear":391,"bibarel":207,"bidoof":207,"binacle":353,
    "bisharp":317,"blacephalon":426,"blastoise":3,"blaziken":131,"blipbug":435,
    "blissey":51,"blitzle":267,"boldore":268,"boltund":440,"bombirdier":503,
    "bonsly":91,"bouffalant":318,"bounsweet":392,"braixen":338,
    "brambleghast":495,"bramblin":495,"braviary":319,"breloom":142,
    "brionne":376,"bronzong":224,"bronzor":224,"brute-bonnet":517,"bruxish":405,
    "budew":158,"buizel":216,"bulbasaur":1,"buneary":220,"bunnelby":340,
    "burmy":213,"butterfree":4,"buzzwole":415,"cacnea":167,"cacturne":167,
    "calyrex":476,"camerupt":162,"capsakid":498,"carbink":361,"carkol":441,
    "carnivine":236,"carracosta":288,"carvanha":160,"cascoon":135,
    "castform":179,"caterpie":4,"celebi":129,"celesteela":418,"centiskorch":447,
    "ceruledge":490,"cetitan":511,"cetoddle":511,"chandelure":308,"chansey":51,
    "charcadet":490,"charizard":2,"charjabug":379,"charmander":2,"charmeleon":2,
    "chatot":228,"cherrim":217,"cherubi":217,"chesnaught":337,"chespin":337,
    "chewtle":439,"chi-yu":532,"chien-pao":530,"chikorita":79,"chimchar":204,
    "chimecho":184,"chinchou":86,"chingling":184,"cinccino":292,"cinderace":431,
    "clamperl":188,"clauncher":355,"clawitzer":355,"claydol":175,"clefable":14,
    "clefairy":14,"cleffa":14,"clobbopus":448,"clodsire":96,"cloyster":39,
    "coalossal":441,"cobalion":325,"cofagrigus":287,"combee":214,
    "combusken":131,"comfey":393,"conkeldurr":272,"copperajah":460,
    "corphish":174,"corsola":113,"corviknight":434,"corvisquire":434,
    "cosmoem":413,"cosmog":413,"cottonee":278,"crabominable":380,
    "crabrawler":380,"cradily":176,"cramorant":444,"cranidos":211,
    "crawdaunt":174,"cresselia":249,"croagunk":235,"crobat":17,"crocalor":479,
    "croconaw":81,"crustle":284,"cryogonal":311,"cubchoo":310,"cubone":46,
    "cufant":460,"cursola":113,"cutiefly":382,"cyclizar":506,"cyndaquil":80,
    "dachsbun":486,"darkrai":252,"darmanitan":282,"dartrix":374,"darumaka":282,
    "decidueye":374,"dedenne":360,"deerling":297,"deino":323,"delcatty":148,
    "delibird":115,"delphox":338,"deoxys":202,"dewgong":37,"dewott":258,
    "dewpider":387,"dhelmise":407,"dialga":244,"diancie":371,"diggersby":340,
    "diglett":21,"dipplin":442,"ditto":66,"dodrio":36,"doduo":36,"dolliv":487,
    "dondozo":513,"donphan":119,"dottler":435,"doublade":349,"dracovish":463,
    "dracozolt":461,"dragalge":354,"dragapult":466,"dragonair":76,
    "dragonite":76,"drakloak":466,"drampa":406,"drapion":234,"dratini":76,
    "drednaw":439,"dreepy":466,"drifblim":219,"drifloon":219,"drilbur":270,
    "drizzile":432,"drowzee":42,"druddigon":315,"dubwool":438,"ducklett":295,
    "dudunsparce":103,"dugtrio":21,"dunsparce":103,"duosion":294,
    "duraludon":465,"durant":322,"dusclops":182,"dusknoir":182,"duskull":182,
    "dustox":135,"dwebble":284,"eelektrik":306,"eelektross":306,"eevee":67,
    "eiscue":457,"ekans":9,"eldegoss":437,"electabuzz":60,"electivire":60,
    "electrike":153,"electrode":44,"elekid":60,"elgyem":307,"emboar":257,
    "emolga":298,"empoleon":205,"enamorus":477,"entei":124,"escavalier":299,
    "espathra":500,"espeon":67,"espurr":348,"eternatus":469,"excadrill":270,
    "exeggcute":45,"exeggutor":45,"exploud":145,"falinks":453,"farfetchd":35,
    "farigiraf":101,"fearow":8,"feebas":178,"fennekin":338,"feraligatr":81,
    "ferroseed":304,"ferrothorn":304,"fezandipiti":542,"fidough":486,
    "finizen":504,"finneon":237,"flaaffy":89,"flabebe":344,"flamigo":510,
    "flapple":442,"flareon":67,"fletchinder":341,"fletchling":341,"flittle":500,
    "floatzel":216,"floette":344,"floragato":478,"florges":344,
    "flutter-mane":518,"flygon":166,"fomantis":388,"foongus":300,
    "forretress":102,"fraxure":309,"frigibax":527,"frillish":301,"froakie":339,
    "frogadier":339,"froslass":186,"frosmoth":455,"fuecoco":479,"furfrou":347,
    "furret":82,"gabite":230,"gallade":140,"galvantula":303,"garbodor":290,
    "garchomp":230,"gardevoir":140,"garganacl":489,"gastly":40,"gastrodon":218,
    "genesect":336,"gengar":40,"geodude":31,"gholdengo":528,"gible":230,
    "gigalith":268,"gimmighoul":528,"girafarig":101,"giratina":248,"glaceon":67,
    "glalie":186,"glameow":221,"glastrier":474,"gligar":104,"glimmet":508,
    "glimmora":508,"gliscor":104,"gloom":18,"gogoat":345,"golbat":17,
    "goldeen":55,"golduck":23,"golem":31,"golett":316,"golisopod":396,
    "golurk":316,"goodra":362,"goomy":362,"gorebyss":188,"gossifleur":437,
    "gothita":293,"gothitelle":293,"gothorita":293,"gouging-fire":544,
    "gourgeist":365,"grafaiai":494,"granbull":105,"grapploct":448,"graveler":31,
    "great-tusk":515,"greavard":509,"greedent":433,"greninja":339,"grimer":38,
    "grimmsnarl":451,"grookey":430,"grotle":203,"groudon":199,"grovyle":130,
    "growlithe":25,"grubbin":379,"grumpig":164,"gulpin":159,"gumshoos":378,
    "gurdurr":272,"guzzlord":420,"gyarados":64,"hakamo-o":408,"happiny":51,
    "hariyama":146,"hatenna":450,"hatterene":450,"hattrem":450,"haunter":40,
    "hawlucha":359,"haxorus":309,"heatmor":321,"heatran":246,"heliolisk":356,
    "helioptile":356,"heracross":108,"herdier":260,"hippopotas":233,
    "hippowdon":233,"hitmonchan":47,"hitmonlee":47,"hitmontop":47,"ho-oh":128,
    "honchkrow":97,"honedge":349,"hoopa":372,"hoothoot":83,"hoppip":92,
    "horsea":54,"houndoom":118,"houndour":118,"houndstone":509,"huntail":188,
    "hydrapple":442,"hydreigon":323,"hypno":42,"igglybuff":16,"illumise":157,
    "impidimp":451,"incineroar":375,"indeedee":458,"infernape":204,"inkay":352,
    "inteleon":432,"iron-boulder":547,"iron-bundle":522,"iron-crown":546,
    "iron-hands":523,"iron-jugulis":524,"iron-leaves":538,"iron-moth":525,
    "iron-thorns":526,"iron-treads":521,"iron-valiant":534,"ivysaur":1,
    "jangmo-o":408,"jellicent":301,"jigglypuff":16,"jirachi":201,"jolteon":67,
    "joltik":303,"jumpluff":92,"jynx":59,"kabuto":70,"kabutops":70,"kadabra":27,
    "kakuna":5,"kangaskhan":53,"karrablast":299,"kartana":419,"kecleon":180,
    "keldeo":334,"kilowattrel":492,"kingambit":317,"kingdra":54,"kingler":43,
    "kirlia":140,"klang":305,"klawf":497,"kleavor":58,"klefki":363,"klink":305,
    "klinklang":305,"koffing":49,"komala":401,"kommo-o":408,"koraidon":535,
    "krabby":43,"kricketot":208,"kricketune":208,"krokorok":281,
    "krookodile":281,"kubfu":470,"kyogre":198,"kyurem":333,"lairon":151,
    "lampent":308,"landorus":332,"lanturn":86,"lapras":65,"larvesta":324,
    "larvitar":126,"latias":196,"latios":197,"leafeon":67,"leavanny":276,
    "lechonk":481,"ledian":84,"ledyba":84,"lickilicky":48,"lickitung":48,
    "liepard":261,"lileep":176,"lilligant":279,"lillipup":260,"linoone":134,
    "litleo":343,"litten":375,"litwick":308,"lokix":483,"lombre":136,
    "lopunny":220,"lotad":136,"loudred":145,"lucario":232,"ludicolo":136,
    "lugia":127,"lumineon":237,"lunala":413,"lunatone":171,"lurantis":388,
    "luvdisc":190,"luxio":209,"luxray":209,"lycanroc":383,"mabosstiff":493,
    "machamp":28,"machoke":28,"machop":28,"magby":61,"magcargo":111,
    "magearna":422,"magikarp":64,"magmar":61,"magmortar":61,"magnemite":34,
    "magneton":34,"magnezone":34,"makuhita":146,"malamar":352,"mamoswine":112,
    "manaphy":250,"mandibuzz":320,"manectric":153,"mankey":24,"mantine":116,
    "mantyke":116,"maractus":283,"mareanie":385,"mareep":89,"marill":90,
    "marowak":46,"marshadow":423,"marshtomp":132,"maschiff":493,
    "masquerain":141,"maushold":485,"mawile":150,"medicham":152,"meditite":152,
    "meganium":79,"melmetal":428,"meloetta":335,"meltan":428,"meowscarada":478,
    "meowstic":348,"meowth":22,"mesprit":242,"metagross":192,"metang":192,
    "metapod":4,"mew":78,"mewtwo":77,"mienfoo":314,"mienshao":314,
    "mightyena":133,"milcery":452,"milotic":178,"miltank":122,"mime-jr":57,
    "mimikyu":404,"minccino":292,"minior":400,"minun":155,"miraidon":536,
    "misdreavus":98,"mismagius":98,"moltres":75,"monferno":204,"morelull":389,
    "morgrem":451,"morpeko":459,"mothim":213,"mr-mime":57,"mr-rime":57,
    "mudbray":386,"mudkip":132,"mudsdale":386,"muk":38,"munchlax":72,
    "munkidori":541,"munna":265,"murkrow":97,"musharna":265,"nacli":489,
    "naclstack":489,"naganadel":424,"natu":88,"necrozma":421,"nickit":436,
    "nidoking":13,"nidoqueen":12,"nidoran-f":12,"nidoran-m":13,"nidorina":12,
    "nidorino":13,"nihilego":414,"nincada":144,"ninetales":15,"ninjask":144,
    "noctowl":83,"noibat":367,"noivern":367,"nosepass":147,"numel":162,
    "nuzleaf":137,"nymble":483,"obstagoon":134,"octillery":114,"oddish":18,
    "ogerpon":543,"oinkologne":481,"okidogi":540,"omanyte":69,"omastar":69,
    "onix":41,"oranguru":394,"orbeetle":435,"oricorio":381,"orthworm":507,
    "oshawott":258,"overqwil":106,"pachirisu":215,"palafin":504,"palkia":245,
    "palossand":397,"palpitoad":273,"pancham":346,"pangoro":346,"panpour":264,
    "pansage":262,"pansear":263,"paras":19,"parasect":19,"passimian":395,
    "patrat":259,"pawmi":484,"pawmo":484,"pawmot":484,"pawniard":317,
    "pecharunt":549,"pelipper":139,"perrserker":22,"persian":22,"petilil":279,
    "phanpy":119,"phantump":364,"pheromosa":416,"phione":250,"pichu":10,
    "pidgeot":6,"pidgeotto":6,"pidgey":6,"pidove":266,"pignite":257,
    "pikachu":10,"pikipek":377,"piloswine":112,"pincurchin":454,"pineco":102,
    "pinsir":62,"piplup":205,"plusle":154,"poipole":424,"politoed":26,
    "poliwag":26,"poliwhirl":26,"poliwrath":26,"poltchageist":539,
    "polteageist":449,"ponyta":32,"poochyena":133,"popplio":376,"porygon":68,
    "porygon-z":68,"porygon2":68,"primarina":376,"primeape":24,"prinplup":205,
    "probopass":147,"psyduck":23,"pumpkaboo":365,"pupitar":126,"purrloin":261,
    "purugly":221,"pyroar":343,"pyukumuku":398,"quagsire":96,"quaquaval":480,
    "quaxly":480,"quaxwell":480,"quilava":80,"quilladin":337,"qwilfish":106,
    "raboot":431,"rabsca":499,"raging-bolt":545,"raichu":10,"raikou":123,
    "ralts":140,"rampardos":211,"rapidash":32,"raticate":7,"rattata":7,
    "rayquaza":200,"regice":194,"regidrago":473,"regieleki":472,"regigigas":247,
    "regirock":193,"registeel":195,"relicanth":189,"rellor":499,"remoraid":114,
    "reshiram":330,"reuniclus":294,"revavroom":505,"rhydon":50,"rhyhorn":50,
    "rhyperior":50,"ribombee":382,"rillaboom":430,"riolu":232,
    "roaring-moon":533,"rockruff":383,"roggenrola":268,"rolycoly":441,
    "rookidee":434,"roselia":158,"roserade":158,"rotom":240,"rowlet":374,
    "rufflet":319,"runerigus":287,"sableye":149,"salamence":191,"salandit":390,
    "salazzle":390,"samurott":258,"sandaconda":443,"sandile":281,"sandshrew":11,
    "sandslash":11,"sandy-shocks":520,"sandygast":397,"sawk":275,"sawsbuck":297,
    "scatterbug":342,"sceptile":130,"scizor":58,"scolipede":277,"scorbunny":431,
    "scovillain":498,"scrafty":285,"scraggy":285,"scream-tail":516,"scyther":58,
    "seadra":54,"seaking":55,"sealeo":187,"seedot":137,"seel":37,
    "seismitoad":273,"sentret":82,"serperior":256,"servine":256,"seviper":170,
    "sewaddle":276,"sharpedo":160,"shaymin":253,"shedinja":144,"shelgon":191,
    "shellder":39,"shellos":218,"shelmet":312,"shieldon":212,"shiftry":137,
    "shiinotic":389,"shinx":209,"shroodle":494,"shroomish":142,"shuckle":107,
    "shuppet":181,"sigilyph":286,"silcoon":135,"silicobra":443,"silvally":399,
    "simipour":264,"simisage":262,"simisear":263,"sinistcha":539,"sinistea":449,
    "sirfetchd":35,"sizzlipede":447,"skarmory":117,"skeledirge":479,
    "skiddo":345,"skiploom":92,"skitty":148,"skorupi":234,"skrelp":354,
    "skuntank":223,"skwovet":433,"slaking":143,"slakoth":143,"sliggoo":362,
    "slither-wing":519,"slowbro":33,"slowking":33,"slowpoke":33,"slugma":111,
    "slurpuff":351,"smeargle":121,"smoliv":487,"smoochum":59,"sneasel":109,
    "sneasler":109,"snivy":256,"snom":455,"snorlax":72,"snorunt":186,
    "snover":239,"snubbull":105,"sobble":432,"solgaleo":413,"solosis":294,
    "solrock":172,"spearow":8,"spectrier":475,"spewpa":342,"spheal":187,
    "spidops":482,"spinarak":85,"spinda":165,"spiritomb":229,"spoink":164,
    "sprigatito":478,"spritzee":350,"squawkabilly":488,"squirtle":3,
    "stakataka":425,"stantler":120,"staraptor":206,"staravia":206,"starly":206,
    "starmie":56,"staryu":56,"steelix":41,"steenee":392,"stonjourner":456,
    "stoutland":260,"stufful":391,"stunfisk":313,"stunky":223,"sudowoodo":91,
    "suicune":125,"sunflora":94,"sunkern":94,"surskit":141,"swablu":168,
    "swadloon":276,"swalot":159,"swampert":132,"swanna":295,"swellow":138,
    "swinub":112,"swirlix":351,"swoobat":269,"sylveon":67,"tadbulb":491,
    "taillow":138,"talonflame":341,"tandemaus":485,"tangela":52,"tangrowth":52,
    "tapu-bulu":411,"tapu-fini":412,"tapu-koko":409,"tapu-lele":410,
    "tarountula":482,"tatsugiri":514,"tauros":63,"teddiursa":110,"tentacool":30,
    "tentacruel":30,"tepig":257,"terapagos":548,"terrakion":326,"thievul":436,
    "throh":274,"thundurus":329,"thwackey":430,"timburr":272,"ting-lu":531,
    "tinkatink":501,"tinkaton":501,"tinkatuff":501,"tirtouga":288,
    "toedscool":496,"toedscruel":496,"togedemaru":403,"togekiss":87,"togepi":87,
    "togetic":87,"torchic":131,"torkoal":163,"tornadus":328,"torracat":375,
    "torterra":203,"totodile":81,"toucannon":377,"toxapex":385,"toxel":446,
    "toxicroak":235,"toxtricity":446,"tranquill":266,"trapinch":166,
    "treecko":130,"trevenant":364,"tropius":183,"trubbish":290,"trumbeak":377,
    "tsareena":392,"turtonator":402,"turtwig":203,"tympole":273,"tynamo":306,
    "type-null":399,"typhlosion":80,"tyranitar":126,"tyrantrum":357,
    "tyrogue":47,"tyrunt":357,"umbreon":67,"unfezant":266,"unown":99,
    "ursaluna":110,"ursaring":110,"urshifu":470,"uxie":241,"vanillish":296,
    "vanillite":296,"vanilluxe":296,"vaporeon":67,"varoom":505,"veluza":512,
    "venipede":277,"venomoth":20,"venonat":20,"venusaur":1,"vespiquen":214,
    "vibrava":166,"victini":255,"victreebel":29,"vigoroth":143,"vikavolt":379,
    "vileplume":18,"virizion":327,"vivillon":342,"volbeat":156,"volcanion":373,
    "volcarona":324,"voltorb":44,"vullaby":320,"vulpix":15,"wailmer":161,
    "wailord":161,"walking-wake":537,"walrein":187,"wartortle":3,"watchog":259,
    "wattrel":492,"weavile":109,"weedle":5,"weepinbell":29,"weezing":49,
    "whimsicott":278,"whirlipede":277,"whiscash":173,"whismur":145,
    "wigglytuff":16,"wiglett":502,"wimpod":396,"wingull":139,"wishiwashi":384,
    "wo-chien":529,"wobbuffet":100,"woobat":269,"wooloo":438,"wooper":96,
    "wormadam":213,"wugtrio":502,"wurmple":135,"wynaut":100,"wyrdeer":120,
    "xatu":88,"xerneas":368,"xurkitree":417,"yamask":287,"yamper":440,
    "yanma":95,"yanmega":95,"yungoos":378,"yveltal":369,"zacian":467,
    "zamazenta":468,"zangoose":169,"zapdos":74,"zarude":471,"zebstrika":267,
    "zekrom":331,"zeraora":427,"zigzagoon":134,"zoroark":291,"zorua":291,
    "zubat":17,"zweilous":323,"zygarde":370,
}


# what each species evolves from, for the ones that evolve from
# something: "garchomp" -> "gabite" -> "gible". Families branch --
# Gardevoir and Gallade both come from Kirlia -- and siblings aren't
# stages of each other, so this, not FAMILY alone, decides it.
PARENT = {
    "abomasnow":"snover","accelgor":"shelmet","aegislash":"doublade",
    "aggron":"lairon","alakazam":"kadabra","alcremie":"milcery",
    "altaria":"swablu","ambipom":"aipom","amoonguss":"foongus",
    "ampharos":"flaaffy","annihilape":"primeape","appletun":"applin",
    "araquanid":"dewpider","arbok":"ekans","arboliva":"dolliv",
    "arcanine":"growlithe","archaludon":"duraludon","archeops":"archen",
    "arctibax":"frigibax","ariados":"spinarak","armaldo":"anorith",
    "armarouge":"charcadet","aromatisse":"spritzee","aurorus":"amaura",
    "avalugg":"bergmite","azumarill":"marill","banette":"shuppet",
    "barbaracle":"binacle","barraskewda":"arrokuda","basculegion":"basculin",
    "bastiodon":"shieldon","baxcalibur":"arctibax","bayleef":"chikorita",
    "beartic":"cubchoo","beautifly":"silcoon","beedrill":"kakuna",
    "beheeyem":"elgyem","bellibolt":"tadbulb","bellossom":"gloom",
    "bewear":"stufful","bibarel":"bidoof","bisharp":"pawniard",
    "blastoise":"wartortle","blaziken":"combusken","blissey":"chansey",
    "boldore":"roggenrola","boltund":"yamper","braixen":"fennekin",
    "brambleghast":"bramblin","braviary":"rufflet","breloom":"shroomish",
    "brionne":"popplio","bronzong":"bronzor","butterfree":"metapod",
    "cacturne":"cacnea","camerupt":"numel","carkol":"rolycoly",
    "carracosta":"tirtouga","cascoon":"wurmple","centiskorch":"sizzlipede",
    "ceruledge":"charcadet","cetitan":"cetoddle","chandelure":"lampent",
    "chansey":"happiny","charizard":"charmeleon","charjabug":"grubbin",
    "charmeleon":"charmander","cherrim":"cherubi","chesnaught":"quilladin",
    "chimecho":"chingling","cinccino":"minccino","cinderace":"raboot",
    "clawitzer":"clauncher","claydol":"baltoy","clefable":"clefairy",
    "clefairy":"cleffa","clodsire":"wooper","cloyster":"shellder",
    "coalossal":"carkol","cofagrigus":"yamask","combusken":"torchic",
    "conkeldurr":"gurdurr","copperajah":"cufant","corviknight":"corvisquire",
    "corvisquire":"rookidee","cosmoem":"cosmog","crabominable":"crabrawler",
    "cradily":"lileep","crawdaunt":"corphish","crobat":"golbat",
    "crocalor":"fuecoco","croconaw":"totodile","crustle":"dwebble",
    "cursola":"corsola","dachsbun":"fidough","darmanitan":"darumaka",
    "dartrix":"rowlet","decidueye":"dartrix","delcatty":"skitty",
    "delphox":"braixen","dewgong":"seel","dewott":"oshawott",
    "diggersby":"bunnelby","dipplin":"applin","dodrio":"doduo",
    "dolliv":"smoliv","donphan":"phanpy","dottler":"blipbug",
    "doublade":"honedge","dragalge":"skrelp","dragapult":"drakloak",
    "dragonair":"dratini","dragonite":"dragonair","drakloak":"dreepy",
    "drapion":"skorupi","drednaw":"chewtle","drifblim":"drifloon",
    "drizzile":"sobble","dubwool":"wooloo","dudunsparce":"dunsparce",
    "dugtrio":"diglett","duosion":"solosis","dusclops":"duskull",
    "dusknoir":"dusclops","dustox":"cascoon","eelektrik":"tynamo",
    "eelektross":"eelektrik","eldegoss":"gossifleur","electabuzz":"elekid",
    "electivire":"electabuzz","electrode":"voltorb","emboar":"pignite",
    "empoleon":"prinplup","escavalier":"karrablast","espathra":"flittle",
    "espeon":"eevee","excadrill":"drilbur","exeggutor":"exeggcute",
    "exploud":"loudred","farigiraf":"girafarig","fearow":"spearow",
    "feraligatr":"croconaw","ferrothorn":"ferroseed","flaaffy":"mareep",
    "flapple":"applin","flareon":"eevee","fletchinder":"fletchling",
    "floatzel":"buizel","floette":"flabebe","floragato":"sprigatito",
    "florges":"floette","flygon":"vibrava","forretress":"pineco",
    "fraxure":"axew","frogadier":"froakie","froslass":"snorunt",
    "frosmoth":"snom","furret":"sentret","gabite":"gible","gallade":"kirlia",
    "galvantula":"joltik","garbodor":"trubbish","garchomp":"gabite",
    "gardevoir":"kirlia","garganacl":"naclstack","gastrodon":"shellos",
    "gengar":"haunter","gholdengo":"gimmighoul","gigalith":"boldore",
    "glaceon":"eevee","glalie":"snorunt","glimmora":"glimmet",
    "gliscor":"gligar","gloom":"oddish","gogoat":"skiddo","golbat":"zubat",
    "golduck":"psyduck","golem":"graveler","golisopod":"wimpod",
    "golurk":"golett","goodra":"sliggoo","gorebyss":"clamperl",
    "gothitelle":"gothorita","gothorita":"gothita","gourgeist":"pumpkaboo",
    "grafaiai":"shroodle","granbull":"snubbull","grapploct":"clobbopus",
    "graveler":"geodude","greedent":"skwovet","greninja":"frogadier",
    "grimmsnarl":"morgrem","grotle":"turtwig","grovyle":"treecko",
    "grumpig":"spoink","gumshoos":"yungoos","gurdurr":"timburr",
    "gyarados":"magikarp","hakamo-o":"jangmo-o","hariyama":"makuhita",
    "hatterene":"hattrem","hattrem":"hatenna","haunter":"gastly",
    "haxorus":"fraxure","heliolisk":"helioptile","herdier":"lillipup",
    "hippowdon":"hippopotas","hitmonchan":"tyrogue","hitmonlee":"tyrogue",
    "hitmontop":"tyrogue","honchkrow":"murkrow","houndoom":"houndour",
    "houndstone":"greavard","huntail":"clamperl","hydrapple":"dipplin",
    "hydreigon":"zweilous","hypno":"drowzee","incineroar":"torracat",
    "infernape":"monferno","inteleon":"drizzile","ivysaur":"bulbasaur",
    "jellicent":"frillish","jigglypuff":"igglybuff","jolteon":"eevee",
    "jumpluff":"skiploom","jynx":"smoochum","kabutops":"kabuto",
    "kadabra":"abra","kakuna":"weedle","kilowattrel":"wattrel",
    "kingambit":"bisharp","kingdra":"seadra","kingler":"krabby",
    "kirlia":"ralts","klang":"klink","kleavor":"scyther","klinklang":"klang",
    "kommo-o":"hakamo-o","kricketune":"kricketot","krokorok":"sandile",
    "krookodile":"krokorok","lairon":"aron","lampent":"litwick",
    "lanturn":"chinchou","leafeon":"eevee","leavanny":"swadloon",
    "ledian":"ledyba","lickilicky":"lickitung","liepard":"purrloin",
    "lilligant":"petilil","linoone":"zigzagoon","lokix":"nymble",
    "lombre":"lotad","lopunny":"buneary","loudred":"whismur","lucario":"riolu",
    "ludicolo":"lombre","lumineon":"finneon","lunala":"cosmoem",
    "lurantis":"fomantis","luxio":"shinx","luxray":"luxio",
    "lycanroc":"rockruff","mabosstiff":"maschiff","machamp":"machoke",
    "machoke":"machop","magcargo":"slugma","magmar":"magby",
    "magmortar":"magmar","magneton":"magnemite","magnezone":"magneton",
    "malamar":"inkay","mamoswine":"piloswine","mandibuzz":"vullaby",
    "manectric":"electrike","mantine":"mantyke","marill":"azurill",
    "marowak":"cubone","marshtomp":"mudkip","masquerain":"surskit",
    "maushold":"tandemaus","medicham":"meditite","meganium":"bayleef",
    "melmetal":"meltan","meowscarada":"floragato","meowstic":"espurr",
    "metagross":"metang","metang":"beldum","metapod":"caterpie",
    "mienshao":"mienfoo","mightyena":"poochyena","milotic":"feebas",
    "mismagius":"misdreavus","monferno":"chimchar","morgrem":"impidimp",
    "mothim":"burmy","mr-mime":"mime-jr","mr-rime":"mr-mime",
    "mudsdale":"mudbray","muk":"grimer","musharna":"munna","naclstack":"nacli",
    "naganadel":"poipole","nidoking":"nidorino","nidoqueen":"nidorina",
    "nidorina":"nidoran-f","nidorino":"nidoran-m","ninetales":"vulpix",
    "ninjask":"nincada","noctowl":"hoothoot","noivern":"noibat",
    "nuzleaf":"seedot","obstagoon":"linoone","octillery":"remoraid",
    "oinkologne":"lechonk","omastar":"omanyte","orbeetle":"dottler",
    "overqwil":"qwilfish","palafin":"finizen","palossand":"sandygast",
    "palpitoad":"tympole","pangoro":"pancham","parasect":"paras",
    "pawmo":"pawmi","pawmot":"pawmo","pelipper":"wingull","perrserker":"meowth",
    "persian":"meowth","pidgeot":"pidgeotto","pidgeotto":"pidgey",
    "pignite":"tepig","pikachu":"pichu","piloswine":"swinub",
    "politoed":"poliwhirl","poliwhirl":"poliwag","poliwrath":"poliwhirl",
    "polteageist":"sinistea","porygon-z":"porygon2","porygon2":"porygon",
    "primarina":"brionne","primeape":"mankey","prinplup":"piplup",
    "probopass":"nosepass","pupitar":"larvitar","purugly":"glameow",
    "pyroar":"litleo","quagsire":"wooper","quaquaval":"quaxwell",
    "quaxwell":"quaxly","quilava":"cyndaquil","quilladin":"chespin",
    "raboot":"scorbunny","rabsca":"rellor","raichu":"pikachu",
    "rampardos":"cranidos","rapidash":"ponyta","raticate":"rattata",
    "reuniclus":"duosion","revavroom":"varoom","rhydon":"rhyhorn",
    "rhyperior":"rhydon","ribombee":"cutiefly","rillaboom":"thwackey",
    "roselia":"budew","roserade":"roselia","runerigus":"yamask",
    "salamence":"shelgon","salazzle":"salandit","samurott":"dewott",
    "sandaconda":"silicobra","sandslash":"sandshrew","sawsbuck":"deerling",
    "sceptile":"grovyle","scizor":"scyther","scolipede":"whirlipede",
    "scovillain":"capsakid","scrafty":"scraggy","seadra":"horsea",
    "seaking":"goldeen","sealeo":"spheal","seismitoad":"palpitoad",
    "serperior":"servine","servine":"snivy","sharpedo":"carvanha",
    "shedinja":"nincada","shelgon":"bagon","shiftry":"nuzleaf",
    "shiinotic":"morelull","silcoon":"wurmple","silvally":"type-null",
    "simipour":"panpour","simisage":"pansage","simisear":"pansear",
    "sinistcha":"poltchageist","sirfetchd":"farfetchd","skeledirge":"crocalor",
    "skiploom":"hoppip","skuntank":"stunky","slaking":"vigoroth",
    "sliggoo":"goomy","slowbro":"slowpoke","slowking":"slowpoke",
    "slurpuff":"swirlix","sneasler":"sneasel","snorlax":"munchlax",
    "solgaleo":"cosmoem","spewpa":"scatterbug","spidops":"tarountula",
    "staraptor":"staravia","staravia":"starly","starmie":"staryu",
    "steelix":"onix","steenee":"bounsweet","stoutland":"herdier",
    "sudowoodo":"bonsly","sunflora":"sunkern","swadloon":"sewaddle",
    "swalot":"gulpin","swampert":"marshtomp","swanna":"ducklett",
    "swellow":"taillow","swoobat":"woobat","sylveon":"eevee",
    "talonflame":"fletchinder","tangrowth":"tangela","tentacruel":"tentacool",
    "thievul":"nickit","thwackey":"grookey","tinkaton":"tinkatuff",
    "tinkatuff":"tinkatink","toedscruel":"toedscool","togekiss":"togetic",
    "togetic":"togepi","torracat":"litten","torterra":"grotle",
    "toucannon":"trumbeak","toxapex":"mareanie","toxicroak":"croagunk",
    "toxtricity":"toxel","tranquill":"pidove","trevenant":"phantump",
    "trumbeak":"pikipek","tsareena":"steenee","typhlosion":"quilava",
    "tyranitar":"pupitar","tyrantrum":"tyrunt","umbreon":"eevee",
    "unfezant":"tranquill","ursaluna":"ursaring","ursaring":"teddiursa",
    "urshifu":"kubfu","vanillish":"vanillite","vanilluxe":"vanillish",
    "vaporeon":"eevee","venomoth":"venonat","venusaur":"ivysaur",
    "vespiquen":"combee","vibrava":"trapinch","victreebel":"weepinbell",
    "vigoroth":"slakoth","vikavolt":"charjabug","vileplume":"gloom",
    "vivillon":"spewpa","volcarona":"larvesta","wailord":"wailmer",
    "walrein":"sealeo","wartortle":"squirtle","watchog":"patrat",
    "weavile":"sneasel","weepinbell":"bellsprout","weezing":"koffing",
    "whimsicott":"cottonee","whirlipede":"venipede","whiscash":"barboach",
    "wigglytuff":"jigglypuff","wobbuffet":"wynaut","wormadam":"burmy",
    "wugtrio":"wiglett","wyrdeer":"stantler","xatu":"natu","yanmega":"yanma",
    "zebstrika":"blitzle","zoroark":"zorua","zweilous":"deino",
}

# words on a card that aren't part of the species
_DROP = {"ex", "v", "vmax", "vstar", "gx", "x", "y", "break", "prime",
         "star", "mega", "radiant", "shining", "hisuian", "galarian",
         "alolan", "paldean", "bloodmoon", "origin", "forme", "form",
         "tera", "ancient", "future"}

# card names that don't reduce to PokeAPI's name by dropping words
_SPECIAL = {
    "mr. mime": "mr-mime", "mime jr.": "mime-jr", "mr. rime": "mr-rime",
    "farfetch'd": "farfetchd", "sirfetch'd": "sirfetchd",
    "type: null": "type-null", "flabébé": "flabebe",
    "nidoran♀": "nidoran-f", "nidoran♂": "nidoran-m",
    "teal mask ogerpon": "ogerpon", "wellspring mask ogerpon": "ogerpon",
    "hearthflame mask ogerpon": "ogerpon",
    "cornerstone mask ogerpon": "ogerpon",
}

_OWNER = re.compile(r"^[^'’]{1,24}['’]s\s+")


def species(card_name):
    """ "Cynthia's Garchomp ex" -> "garchomp", "Iron Hands ex" ->
    "iron-hands". None if it isn't a known Pokemon."""
    if not card_name:
        return None
    s = unicodedata.normalize("NFC", card_name.strip())
    s = _OWNER.sub("", s).strip().lower().replace("’", "'")
    if s in _SPECIAL:
        return _SPECIAL[s]
    words = [w for w in s.split() if w not in _DROP]
    if not words:
        return None
    if " ".join(words) in _SPECIAL:
        return _SPECIAL[" ".join(words)]
    # whole name first ("iron-hands"), then the first word ("garchomp"
    # from a longer card name), then the last ("ogerpon" from a mask)
    for key in ("-".join(words), "".join(words), words[0], words[-1]):
        if key in FAMILY:
            return key
    return None


def family(card_name):
    """The evolution chain number for a card's Pokemon, or None."""
    sp = species(card_name)
    return FAMILY.get(sp) if sp else None


def _ancestors(sp):
    seen = []
    while sp in PARENT and sp not in seen:
        sp = PARENT[sp]
        seen.append(sp)
    return seen


def stages_of_one(a, b):
    """
    True if one card's Pokemon evolves into the other's (Gible, Gabite,
    Garchomp), or they're the same species (Mega Starmie ex and Starmie).
    False for anything else, siblings included (Gardevoir and Gallade).
    None if either Pokemon isn't in the table, so the caller can decide.
    """
    sa, sb = species(a), species(b)
    if not sa or not sb:
        return None
    return sa == sb or sa in _ancestors(sb) or sb in _ancestors(sa)
